[features]
seeds = false
skip-lint = false
[programs.localnet]
demo1 = "GAWkZmby7R7jX7LcJEUUsvrJuEJ7VZ2eugDH3snPoM4P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/frangiskos/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
