[features]
seeds = false
skip-lint = false
[programs.localnet]
nft_staking_demo = "JUM2T3uHhcjeGNFdrpDnQ3gfP8Fa4jfgikMVReundXG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/frangiskos/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
